Create 4-gradient-optimization_cn.ipynb
tencent-quantum-lab/tensorcircuit pull request #1
Opened 2022-05-19 10:48 UTC by SexyCarrots

2022-05-20 07:23 UTC, refraction-ray commented on docs/source/whitepaper/4-gradient-optimization_cn.ipynb
> +    "我们现在展示如何在 TensorCircuit 中实现此类电路，以及如何使用机器学习后端之一轻松高效地计算成本函数和梯度。\n",
成本函数-》损失函数

2022-05-20 07:23 UTC, refraction-ray commented on docs/source/whitepaper/4-gradient-optimization_cn.ipynb
> +    "举个例子，我们取 $n=3, k=2$ ，设置 TensorFlow 作为我们的后端，定义一个能量成本函数来最小化\n",
能量损失函数

2022-05-20 07:26 UTC, refraction-ray commented on docs/source/whitepaper/4-gradient-optimization_cn.ipynb
> +    "我们建议始终使用 ``jit``，只要功能是 ``张量输入，张量输出``，我们已经努力使电路模拟器的各个方面都与 JIT 兼容。"
只要函数是``张量输入，张量输出``的形式

2022-05-20 07:27 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "# 密度矩阵和混合状态演化"
混态演化

2022-05-20 07:27 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "TensorCircuit 提供了两种模拟嘈杂、混合状态量子演化的方法。\n",
含噪声、混态量子演化

2022-05-20 07:27 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "$n$ 量子比特的全密度矩阵模拟是通过使用 ``tc.DMCircuit(n)`` 提供的，然后将量子操作——包括单一门以及由克劳斯算子指定的一般量子操作——添加到电路中。\n",
单一 -> 幺正

2022-05-20 07:28 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "$n$ 量子比特的全密度矩阵模拟是通过使用 ``tc.DMCircuit(n)`` 提供的，然后将量子操作——包括单一门以及由克劳斯算子指定的一般量子操作——添加到电路中。\n",
克劳斯， keep in English， Kraus

2022-05-20 07:28 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "相对于通过 ``tc.Circuit`` 对 $n$ 个量子比特进行纯态模拟，全密度矩阵模拟是内存密集型的两倍，因此可模拟的最大系统大小将是纯态情况下可以模拟的一半。\n",
全密度矩阵模拟会占据两倍内存

2022-05-20 07:28 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "内存密集度较低的选项是使用标准的 ``tc.Circuit(n)`` 对象并通过蒙特卡罗轨迹方法随机模拟开放系统演化。"
内存需求较小的

2022-05-20 07:29 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "dmc.general_kraus([K0, K1], 0)  # 将具有克劳斯算子 [K0,K1] 的通道应用于 qubit 0"
Kraus

2022-05-20 07:30 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "事实上，TensorCircuit 包含用于返回许多公共通道的 Kraus 算子的内置方法，包括振幅阻尼、去极化、相位阻尼和复位通道。"
常见量子通道

2022-05-20 07:30 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "对于纯状态输入，蒙特卡洛方法可用于使用 ``tc.Circuit`` 而不是“tc.DMCircuit”对嘈杂的量子演化进行采样，其中混合状态是用纯状态的集合有效模拟的。\n",
纯状态->纯态

2022-05-20 07:31 UTC, refraction-ray commented on docs/source/whitepaper/5-density-matrix_cn.ipynb
> +    "通过使用 ``unitary_kraus`` 而不是 ``general_kraus``，可以更有效地处理 Kraus 算子都是幺正矩阵（直到一个常数因子）的通道的蒙特卡罗模拟。"
(可相差一个常数因子)

2022-05-20 07:32 UTC, refraction-ray requested changes
several very small translation issues should be fixed

2022-05-20 09:47 UTC, SexyCarrots commented
# Revision Updated

2022-05-22 08:13 UTC, refraction-ray approved these changes
LGTM

2022-05-22 08:21 UTC, merged