Create torch_qml_cn.ipynb
tencent-quantum-lab/tensorcircuit pull request #14
Opened 2022-06-09 13:24 UTC by SexyCarrots

2022-06-09 13:27 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "# PyTorch 中的 QML"
使用 PyTorch 进行量子机器学习

2022-06-09 13:28 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "# 我们使用 tensorflow 和 jax 后端加载和预处理数据集作为之前的 notebook\n",
我们使用和之前 notebook 相同的数据集与预处理

2022-06-09 13:29 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "## 批处理版\n",
版本

2022-06-09 13:29 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "现在让我们尝试使用矢量化版本来加快批量输入处理。请注意，``tf.vectorized_map`` 本质上是如何帮助批处理管道的。"
向量化

2022-06-09 13:30 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "现在让我们尝试使用矢量化版本来加快批量输入处理。请注意，``tf.vectorized_map`` 本质上是如何帮助批处理管道的。"
本质上是 ``tf.vectorized_map`` 帮助了批处理

2022-06-09 13:30 UTC, refraction-ray commented on docs/source/tutorials/torch_qml_cn.ipynb
> +    "# 测试 PyTorch 函数的 AD 容量\n",
容量 -> 支持

2022-06-09 13:31 UTC, refraction-ray requested changes
Great work, several minor translation changes required

2022-06-09 15:14 UTC, SexyCarrots commented
# Ready to GO

2022-06-10 02:03 UTC, refraction-ray approved these changes
LGTM

2022-06-10 02:09 UTC, merged