Create qaoa_cn.ipynb
tencent-quantum-lab/tensorcircuit pull request #33
Opened 2022-07-12 00:51 UTC by SexyCarrots

# Ready to Go

2022-07-12 02:07 UTC, refraction-ray commented on docs/source/tutorials/qaoa.ipynb
> +    "where $\\sigma^{z}_{i}$ is the Pauli-z matrix on $i$th qubit and $C_{ij}$ is the weight of the edge between nodes $i$ and $j$. We set $C_{ij}=1$ for simplicity. If $\\sigma^{z}_{i}=\\sigma^{z}_{
a $ is missing?

2022-07-12 02:08 UTC, refraction-ray commented on docs/source/tutorials/qaoa_cn.ipynb
> +    "# 量子逼近优化算法 (QAOA)"
量子近似优化算法

2022-07-12 02:08 UTC, refraction-ray commented on docs/source/tutorials/qaoa_cn.ipynb
> +    "QAOA 是一种混合经典量子算法，它结合了量子电路和这些电路的经典优化。\n",
结合了量子电路与经典优化

2022-07-12 02:09 UTC, refraction-ray commented on docs/source/tutorials/qaoa_cn.ipynb
> +    "如果 $\\sigma^{z}_{i}= -\\sigma^{z}_{j}$, $i\\in S, j\\in S \\backslash V$ 或 $i\\in S \\backslash V，j\\ 以新元为单位。\n",
missing $?

2022-07-12 02:11 UTC, refraction-ray commented on docs/source/tutorials/qaoa_cn.ipynb
> +    "如果 $\\sigma^{z}_{i}= -\\sigma^{z}_{j}$, $i\\in S, j\\in S \\backslash V$ 或 $i\\in S \\backslash V，j\\ 以新元为单位。\n",
~~以新元为单位~~

2022-07-12 02:12 UTC, refraction-ray requested changes
Some notation syntax requires further double-check

2022-07-12 03:10 UTC, SexyCarrots commented on docs/source/tutorials/qaoa.ipynb
> +    "where $\\sigma^{z}_{i}$ is the Pauli-z matrix on $i$th qubit and $C_{ij}$ is the weight of the edge between nodes $i$ and $j$. We set $C_{ij}=1$ for simplicity. If $\\sigma^{z}_{i}=\\sigma^{z}_{
My bad

2022-07-12 03:23 UTC, SexyCarrots commented
# Upadated

2022-07-12 04:24 UTC, refraction-ray commented
<img width="1085" alt="Screen Shot 2022-07-12 at 12 23 26 PM" src="https://user-images.githubusercontent.com/35157286/178408088-c3b96f15-36b0-431b-baba-98d0117c3df4.png">
<img width="226" alt="Screen Shot 2022-07-12 at 12 23 56 PM" src="https://user-images.githubusercontent.com/35157286/178408139-b7b3f0c3-7278-4f2c-8859-c5ac21435795.png">
公式排版还是都有些问题

2022-07-12 04:25 UTC, SexyCarrots commented
奇怪，我直接从原版复制粘贴的。中文版应该没有问题

2022-07-12 04:49 UTC, SexyCarrots commented
# Readt to GO

2022-07-12 06:06 UTC, refraction-ray commented on docs/source/tutorials/qaoa_cn.ipynb
> +    "显然，$S $ 和 S\\backslash V$ 之间的边数在从基态解码的图结构中最大化。"
$S $ 和 $S\\backslash V$

2022-07-12 18:02 UTC, SexyCarrots commented
现在是没有问题的，不能看源码，得看preview的效果

2022-07-13 01:27 UTC, refraction-ray approved these changes

2022-07-13 01:27 UTC, refraction-ray commented
其实还是有一点点问题，我 merge 下来改一下吧

2022-07-13 01:29 UTC, merged