Add files via upload
tencent-quantum-lab/tensorcircuit pull request #4
Opened 2022-05-25 00:41 UTC by SexyCarrots

# Ready to GO

2022-05-25 01:36 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "我们需要在各种量子算法中评估电路上许多泡利弦项的总和，VQE 中哈密顿量 $H$ 的基态准备就是一个典型的例子。\n",
弦 -> 字符串

2022-05-25 01:36 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "我们需要在各种量子算法中评估电路上许多泡利弦项的总和，VQE 中哈密顿量 $H$ 的基态准备就是一个典型的例子。\n",
基态准备 -> 基态制备

2022-05-25 01:37 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "我们以横向场模型（TFIM）为例，其内容为\n",
内容 -> 哈密顿量

2022-05-25 01:38 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "# 我们使用的电路 ansatz 如下图所示，双量子比特门是梯形布局\n",
梯形->阶梯型

2022-05-25 01:39 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "VQE 训练循环（值和 grad 函数不可知）"
（支持任意梯度函数形式）

2022-05-25 01:40 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "这可以通过在两阶段过程中从泡利结构列表转换来以后端不可知的方式提供。\n",
不可知 -> 无关
提供 -> 实现

2022-05-25 01:41 UTC, refraction-ray commented on docs/source/whitepaper/6-2-pauli-string-expectation_cn.ipynb
> +    "TFIM 哈密顿量，作为短程自旋哈密顿量，承认有效的矩阵乘积算子表示。再次强调，这是一个使用 TensorCircuit 的两阶段过程。\n",
承认 -> 具有
~~再次强调~~

2022-05-25 01:42 UTC, refraction-ray requested changes
Several minor translation issues to be fixed

2022-05-25 01:46 UTC, refraction-ray commented
And what is the PR title about 😂

2022-05-25 20:00 UTC, SexyCarrots commented
my local repo just turn wild. I had to upload it manually through the GitHub website lol.

2022-05-25 20:01 UTC, SexyCarrots commented
# Revised

2022-05-26 01:54 UTC, refraction-ray approved these changes
LGTM

2022-05-26 01:58 UTC, merged