Create 6-4-quoperator_cn.ipynb
tencent-quantum-lab/tensorcircuit pull request #9
Opened 2022-06-03 04:52 UTC by SexyCarrots

2022-06-03 12:10 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "当与其他成分交互时，它们的行为类似于矩阵/向量（列或行），而内部结构由张量网络维护以提高效率和紧凑性。\n",
成分->组件

2022-06-03 12:12 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "定义 ``QuOperator`` 的惯例是首先给出 ``out_edges``（矩阵的左索引或行索引），然后给出 ``in_edges``（矩阵的右索引或列索引）。\n",
惯例-》 约定

2022-06-03 12:13 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "## QuVector 作为电路的输入状态\n",
状态-> 量子态

2022-06-03 12:13 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "由于 QuVector 表现得像一个具有更紧凑表示的实向量，我们可以以 QuVector 的形式而不是普通的 numpy 数组向量来提供电路输入状态。"
~~实~~向量

2022-06-03 12:13 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "## QuVector 作为电路的输出状态\n",
状态->量子态

2022-06-03 12:14 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "# 电路构成示例\n",
构成->组合

2022-06-03 12:14 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "对电路的输出状态进行评估的矩阵也可以用 QuOperator 来表示，这对于一些格模型哈密顿量来说是非常强大和高效的。"
格模型-》格点模型

2022-06-03 12:15 UTC, refraction-ray commented on docs/source/whitepaper/6-4-quoperator_cn.ipynb
> +    "# 一般的 mpo 门 API 只是 ``Circuit.mpo()``\n",
~~只~~是

2022-06-03 12:15 UTC, refraction-ray requested changes
Several minor translation issue to be fixed

2022-06-04 11:57 UTC, SexyCarrots commented
# Ready to Go

2022-06-05 04:01 UTC, refraction-ray approved these changes
LGTM

2022-06-05 04:03 UTC, merged